version: "3"
services:
  php-telegram:
    image: nataha-php-telegram:debug
    build:
      context: ./
      dockerfile: configs/php74.dockerfile
    environment:
      - IS_DEBUG=${IS_DEBUG}
      - IDENT=${IDENT}
      - MAX_MESSAGE_LENGTH=${MAX_MESSAGE_LENGTH}
      - FLOCK_SLEEP_INTERVAL=${FLOCK_SLEEP_INTERVAL}
      - MAX_DB_READ_TRY=${MAX_DB_READ_TRY}
      - ID_CREATOR=${ID_CREATOR}
      - ID_CHAT=${ID_CHAT}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PDO_MEME_DSN=${PDO_MEME_DSN}
      - MAX_WORDS_COUNT=${MAX_WORDS_COUNT}
      - PHP_IDE_CONFIG=serverName=nataha.local
      - XDEBUG_SESSION=1
    volumes:
      - ./php:/var/www
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  php-twitch:
    image: nataha-php-telegram:debug
    build:
      context: ./
      dockerfile: configs/php74.dockerfile
    environment:
      - TWITCH_DEFAULT_SERVER=${TWITCH_DEFAULT_SERVER}
      - TWITCH_DEFAULT_PORT=${TWITCH_DEFAULT_PORT}
      - TWITCH_USERNAME=${TWITCH_USERNAME}
      - TWITCH_PASSWORD=${TWITCH_PASSWORD}
      - TWITCH_CHANNEL_NAME=${TWITCH_CHANNEL_NAME}
      - DISCORD_SERVICE_HOSTNAME=${DISCORD_SERVICE_HOSTNAME}
      - YA_CLOUD_TOKEN=${YA_CLOUD_TOKEN}
      - YA_CLOUD_FOLDER=${YA_CLOUD_FOLDER}
      - USE_DISCORD=${USE_DISCORD}
      - IDENT=${IDENT}
      - PHP_IDE_CONFIG=serverName=nataha.local
      - XDEBUG_SESSION=1
    volumes:
      - ./php:/var/www
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: ["php", "twitch_ep.php"]
  nginx:
    image: library/nginx:alpine
    environment:
      - NGINX_DOMAIN=${NGINX_DOMAIN}
      - NGINX_PHP_HOST=${NGINX_PHP_HOST}
    ports:
      - "8001:80"
    volumes:
    - ./php:/var/www
    - ./configs/nginx.conf:/etc/nginx/templates/site.conf.template
    depends_on:
      - php-telegram
  node:
    image: nataha-node:debug
    build:
      context: ./
      dockerfile: configs/node.dockerfile
    environment:
      NODE_ENV: "development"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    volumes:
      - ./js:/home/node/app
    user: "node"
    ports:
    - "9229:9229"
    depends_on:
      - nginx
    #entrypoint: ["node", "--inspect",  "--inspect-brk=0.0.0.0", "/home/node/app/discord.js"]