services:
  php-telegram:
    build:
      context: ./
      dockerfile: configs/php84.dockerfile
      target: php_84_prod
    image: nataha-php-telegram:1.0
    environment:
      - IS_DEBUG=${IS_DEBUG}
      - IDENT=${IDENT}
      - MAX_MESSAGE_LENGTH=${MAX_MESSAGE_LENGTH}
      - FLOCK_SLEEP_INTERVAL=${FLOCK_SLEEP_INTERVAL}
      - MAX_DB_READ_TRY=${MAX_DB_READ_TRY}
      - ID_CREATOR=${ID_CREATOR}
      - ID_CHAT=${ID_CHAT}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PDO_MEME_DSN=${PDO_MEME_DSN}
      - MAX_WORDS_COUNT=${MAX_WORDS_COUNT}
  php-twitch:
    build:
      context: ./
      dockerfile: configs/php84.dockerfile
      target: php_84_prod
    image: nataha-php-telegram:1.0
    environment:
      - TWITCH_DEFAULT_SERVER=${TWITCH_DEFAULT_SERVER}
      - TWITCH_DEFAULT_PORT=${TWITCH_DEFAULT_PORT}
      - TWITCH_USERNAME=${TWITCH_USERNAME}
      - TWITCH_PASSWORD=${TWITCH_PASSWORD}
      - TWITCH_CHANNEL_NAME=${TWITCH_CHANNEL_NAME}
      - DISCORD_SERVICE_HOSTNAME=${DISCORD_SERVICE_HOSTNAME}
      - YA_CLOUD_TOKEN=${YA_CLOUD_TOKEN}
      - YA_CLOUD_FOLDER=${YA_CLOUD_FOLDER}
      - USE_DISCORD=${USE_DISCORD}
      - IDENT=${IDENT}
    entrypoint: ["php", "twitch_ep.php"]
  nginx:
    image: nataha-nginx:1.0
    build:
      context: ./
      dockerfile: configs/nginx.prod.dockerfile
    environment:
      - NGINX_DOMAIN=${NGINX_DOMAIN}
      - NGINX_PHP_HOST=${NGINX_PHP_HOST}
    ports:
      - "8001:80"
    depends_on:
      - php-telegram
    links:
      - php-telegram
  node:
    image: nataha-node:1.0
    build:
      context: ./
      dockerfile: configs/node.dockerfile
      target: node_prod
    environment:
      NODE_ENV: "production"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    user: "node"
    depends_on:
      - nginx