version: "3"
services:
  php:
    build:
      context: ./php
      dockerfile: php74.dockerfile
    environment:
      - PHP_IDE_CONFIG=serverName=nataha.local
    volumes:
      - ./php:/var/www
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  nginx:
    image: library/nginx:alpine
    ports:
      - "8001:80"
    volumes:
    - ./php:/var/www
    - ./configs/nginx.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
    links:
      - php
  redis:
    image: library/redis:alpine
  node:
    build:
      context: ./js
      dockerfile: Dockerfile
    env_file:
      - configs/vars.env
    environment:
      NODE_ENV: "development"
    volumes:
      - ./js:/home/node/app
    user: "node"
    ports:
    - "9229:9229"
    entrypoint: ["node", "--inspect-brk=0.0.0.0", "/home/node/app/discord.js"]