version: "3"
services:
  php-twitch:
    build:
      context: ./php
      dockerfile: php74.prod.dockerfile
    env_file:
      - configs/vars.env
    entrypoint: ["php", "twitch_ep.php"]
  php-telegram:
    build:
      context: ./php
      dockerfile: php74.prod.dockerfile
    env_file:
      - configs/vars.env
  nginx:
    image: library/nginx:alpine
    ports:
      - "8001:80"
    depends_on:
      - php-telegram
    links:
      - php-telegram
  node:
    build:
      context: ./js
      dockerfile: Dockerfile
    env_file:
      - configs/vars.env
    environment:
      NODE_ENV: "development"
    volumes:
      - ./js:/home/node/app
    user: "node"
    ports:
    - "9229:9229"
    #entrypoint: ["node", "--inspect",  "--inspect-brk=0.0.0.0", "/home/node/app/discord.js"]
    #entrypoint: ["npm", "update"]