version: "3"
services:
  php-twitch:
    build:
      context: .
      dockerfile: php74.dockerfile
    env_file:
      - configs/vars.env
    volumes:
      - ./php:/var/www
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: ["php", "twitch_ep.php"]
  php-telegram:
    build:
      context: .
      dockerfile: php74.dockerfile
    env_file:
      - configs/vars.env
    volumes:
      - ./php:/var/www
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  nginx:
    image: library/nginx:alpine
    ports:
      - "8001:80"
    volumes:
    - ./php:/var/www
    - ./configs/nginx.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php-telegram
    links:
      - php-telegram
  node:
    build:
      context: ./
      dockerfile: node.dockerfile
    env_file:
      - configs/vars.env
    volumes:
      - ./js:/home/node/app
    user: "node"
    ports:
    - "9229:9229"
    #entrypoint: ["node", "--inspect",  "--inspect-brk=0.0.0.0", "/home/node/app/discord.js"]
    #entrypoint: ["npm", "update"]