apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.74.prod.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nataha-nginx
  name: nataha-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nataha-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.74.prod.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/nataha-telegram-bot-default: "true"
        io.kompose.service: nataha-nginx
    spec:
      containers:
        - image: nataha-nginx:1.0
          name: nataha-nginx
          ports:
            - containerPort: 80
              hostPort: 8001
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
