apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.74.prod.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nataha-php-telegram
  name: nataha-php-telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nataha-php-telegram
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.74.prod.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/nataha-telegram-bot-default: "true"
        io.kompose.service: nataha-php-telegram
    spec:
      containers:
        - env:
            - name: IS_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: IS_DEBUG
                  name: vars-env
            - name: FLOCK_SLEEP_INTERVAL
              valueFrom:
                configMapKeyRef:
                  key: FLOCK_SLEEP_INTERVAL
                  name: vars-env
            - name: IDENT
              valueFrom:
                configMapKeyRef:
                  key: IDENT
                  name: vars-env
            - name: ID_CHAT
              valueFrom:
                configMapKeyRef:
                  key: ID_CHAT
                  name: vars-env
            - name: ID_CREATOR
              valueFrom:
                configMapKeyRef:
                  key: ID_CREATOR
                  name: vars-env
            - name: MAX_DB_READ_TRY
              valueFrom:
                configMapKeyRef:
                  key: MAX_DB_READ_TRY
                  name: vars-env
            - name: MAX_MESSAGE_LENGTH
              valueFrom:
                configMapKeyRef:
                  key: MAX_MESSAGE_LENGTH
                  name: vars-env
            - name: MAX_WORDS_COUNT
              valueFrom:
                configMapKeyRef:
                  key: MAX_WORDS_COUNT
                  name: vars-env
            - name: PDO_MEME_DSN
              valueFrom:
                configMapKeyRef:
                  key: PDO_MEME_DSN
                  name: vars-env
            - name: PHP_IDE_CONFIG
              valueFrom:
                configMapKeyRef:
                  key: PHP_IDE_CONFIG
                  name: vars-env
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: TELEGRAM_BOT_TOKEN
                  name: vars-env
            - name: XDEBUG_SESSION
              valueFrom:
                configMapKeyRef:
                  key: XDEBUG_SESSION
                  name: vars-env
          image: nataha-php-telegram:1.0
          name: nataha-php-telegram
          resources: {}
      restartPolicy: Always
status: {}
